version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - laravel

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
